version: '2.1'

services:
  localstack:
    container_name: ${CONTAINER_NAME}
    image: localstack/localstack
    hostname: ${CONTAINER_NAME}
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8001:8001"
    environment:
      - SERVICES=${SERVICES}
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - DEFAULT_REGION=sa-east-1
      - http_proxy=
      - https_proxy=
      - DISABLE_CORS_CHECKS=1
    volumes:
      - "./entrypoint.d:/docker-entrypoint-initaws.d"
