server:
  servlet:
    context-path: addressprocessor
  port: 8081

spring:
  mvc:
    servlet:
      path: addressprocessor
  application:
    name: addressprocessor
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'